### ISSUE TITLE
Multiple Credentials and Auto Login

### ISSUE THREAD

**Issue by Shashwat1729** [shaitanu/bitswifi-extension#1]

**Comment by Shashwat1729** [comment]
[BITS Wifi Auto Login.zip](https://github.com/user-attachments/files/17005251/BITS.Wifi.Auto.Login.zip)
This solves the current issues

**Comment by shaitanu** [comment]
Multiple credentials can and random picking can have issues if one of the id has data limit or no of login exceeded. For managing multiple credentials you need a way to delete and change credentials if entered wrong or the password is changed. As I made this extension for the browser constant internet connectivity check is not needed as you are already working on browser, you will realize that you are logged out. For constant internet check and auto logging on the base of that I made another script. 
This is script exists  just to automate the login steps only.
